---
title: "Mapping Extended"
subtitle: "How does "
author: "Yuelin Jiang"
date: "11/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyverse",
               "magrittr",
               "hurricaneexposuredata",
               "drat",
               "maps",
               "tmap",
               "sf",
               "viridis",
               "sp",
               "kableExtra")
```

## Data Cleaning

## prepare FEMA funds data
```{r, echo=FALSE, message=FALSE}

fema <- read.csv("hurricane.csv", header = TRUE)
options(scipen=999)
fema$state <- tolower(fema$state)
fema$county <- tolower(fema$county)
fema %<>% dplyr::select(disasterNumber, date, state, county, projectAmount, federalShareObligated)
names(fema) <- c("disaster", "date", "region", "subregion", "projectAmount", "federalShare")
# Separate county data, sum projectAmount, federalShareObligated by disaster and county
countyHurr <- fema %>% dplyr::filter(subregion!= "statewide")
countyFund <- countyHurr %>% dplyr::group_by(disaster, region, subregion, date) %>% dplyr::select(projectAmount, federalShare) %>% summarise_each(funs(sum)) 

# Separate statewide data, sum projectAmount, federalShareObligated by disaster and state
stateHurr <- fema %>% dplyr::filter(subregion=="statewide")
stateFund <- stateHurr %>% dplyr::group_by(disaster, region, date) %>% dplyr::select(projectAmount, federalShare) %>% summarise_each(funs(sum)) 


```


```{r}
kable(head(countyFund)) %>% kableExtra::kable_classic()

```

## prepare location


## prepare map data
```{r, echo=FALSE}
## select states 
StatesInt <- c("texas","oklahoma","kansas","louisiana","arkansas","missouri","iowa","wisconsin","michigan","illinois","indiana","ohio","kentucky","tennessee","alabama","mississippi","florida","georgia","south carolina","north carolina","virginia","west virginia","maryland","delaware","pennsylvania","new jersey","new york","connecticut","rhode island","massachusetts","vermont","new hampshire","maine")

MainStates <- map_data("county", StatesInt)

# Hurrican Harvey Incident Period August 23, 2017 - September 15, 2017
harvey <- countyHurr %>% dplyr:: filter((date >= "2017-08-23") & (date <= "2017-09-15"))

# Hurricane Sandy : October 27, 2012 - November 8, 2012
sandy <- countyHurr %>% dplyr:: filter((date >= "2012-10-27") & (date <= "2012-11-08"))
```

```{r}
# add locations on fund dataframe

harvey <- merge(MainStates,harvey,by=c("region","subregion"))
sandy <- merge(MainStates,sandy,by=c("region","subregion"))
```

### Make map plots of Hurricane Harvey's received federal funds by county
```{r}
harveyS <- c("texas","louisiana","arkansas","missouri","kentucky","tennessee","alabama","mississippi","florida","georgia","south carolina","north carolina")
harveyStates <- map_data("county", harveyS)

harveyPlot <- ggplot() + 
  geom_polygon(data=harveyStates, aes(x=long, y=lat, group=group),colour="black",fill="white")+
  geom_polygon(data=harvey, aes(x = long, y = lat, group = group, fill = federalShare/projectAmount))+
  labs(fill="Federal Aid Amount (USD)") + 
  ggtitle("Harvey-2017") +
  theme(plot.title = element_text(hjust = 0.5))

harveyPlot
```
### Make map plots of Hurricane Sandy's received federal funds by county
```{r}
sandyS <- c("virginia","west virginia","maryland","delaware","pennsylvania","new jersey","new york","connecticut","rhode island","massachusetts","vermont","new hampshire", "maine" )
sandyStates <- map_data("county", sandyS)

sandyPlot <- ggplot() + 
  geom_polygon(data=sandyStates, aes(x=long, y=lat, group=group),colour="black",fill="white")+
  geom_polygon(data=sandy, aes(x = long, y = lat, group = group, fill = federalShare/projectAmount), color = "transparent")+
  labs(fill="Federal Aid Amount (USD)") + 
  ggtitle("Sandy-2012") +
  theme(plot.title = element_text(hjust = 0.5))

sandyPlot
```
### Plot total funds

```{r}
kable(head(stateFund)) %>% kable_classic()

ggplot(data = stateFund) +
  geom_point(aes(x = date, y = federalShare/projectAmount, color = region))
```

